### ISSUE TITLE
Resolution of blocking API issues

### ISSUE THREAD

**Issue by Marak** [pyhedgehog/hook.io-sdk-python#4]
@pyhedgehog -

I believe I have resolved the following issues? If not, many more.

https://github.com/bigcompany/hook.io/issues/240
https://github.com/bigcompany/hook.io/issues/241
https://github.com/bigcompany/hook.io/issues/245

Could we get this repo updated and ready for release? I'm ready to add links to this project from hook.io and it's documentation.

**Comment by pyhedgehog** [comment]
Seems that I'll need update interfaces and tests.

Sorry, but this week (including weekends) I will have no spare time. I hope that next weekends will be easier.
